name: Extract Version
description: Extract version from release tag

inputs:
  tag:
    description: Release tag name
    required: true

outputs:
  version:
    description: Extracted version without 'v' prefix
    value: ${{ steps.get_version.outputs.version }}

runs:
  using: composite
  steps:
    - name: ðŸ” Extract version from tag
      id: get_version
      shell: bash
      run: |
        VERSION="${{ inputs.tag }}"
        VERSION="${VERSION#v}"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"
