site_name: MkDocs Simple Blog
repo_name: FernandoCelmer/mkdocs-simple-blog
repo_url: https://github.com/FernandoCelmer/mkdocs-simple-blog
site_url: https://www.fernandocelmer.com
copyright: Fernando Celmer

plugins:
  - search
  - simple-blog-posts

nav:
    - Home: index.md
    - Getting Started: nav/getting-started.md
    - Blog:
      - Blog: blog.md
      - Blog List: nav/components/blog-list.md
      - Blog Sidebar: nav/components/blog-sidebar.md
    - Components:
      - Sidebar: nav/components/sidebar.md
      - Top Menu: nav/components/top-menu.md
      - Preview: nav/components/preview.md
      - Footer: nav/components/footer.md
      - Site Name: nav/components/site-name.md
      - Standard Title: nav/components/standard-title.md
    - Styles:
      - Highlight.js: nav/styles/highlightjs.md
      - Favicon: nav/styles/favicon.md
      - Colors: nav/styles/colors.md
      - Logo: nav/styles/logo.md
      - Fonts: nav/styles/fonts.md
      - Page Metadata: nav/styles/metadata.md
    - Development:
      - Development Guide: nav/development/development-guide.md
      - Testing: nav/development/testing.md
      - Release Notes: nav/development/release-notes.md

theme:
  name: simple-blog
  favicon: assets/favicon.ico
  logo: assets/logo.png
  theme_style: light
  site_name_style: bold
  title_style: bold
  sidebar: true
  navigation_depth: 2
  highlightjs: true
  blog:
    layout: compact
    author: Fernando Celmer
    github: FernandoCelmer
  colors:
    text: black
    title: black
    primary: black
    background: white
  components:
    site_name: true
    title: true
    menu: true
    preview: true
    footer: true
  hljs_languages:
    - yaml
    - python

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.superfences

extra_javascript:
 - assets/custom.js
