"""Regression tests for issue #70 — pymdown-extensions elements must follow theme CSS."""

import unittest
from pathlib import Path

ROOT_DIR = Path(__file__).parent.parent


class TestPymdownExtensionsCss(unittest.TestCase):
    """Elements generated by pymdown-extensions must use theme color variables."""

    def _read(self, relative_path):
        return (ROOT_DIR / relative_path).read_text()

    def test_admonition_uses_theme_variables(self):
        css = self._read("template/assets/css/main.css")
        self.assertIn(".admonition {", css)
        self.assertIn("var(--primary)", css.split(".admonition {", 1)[1][:300])

    def test_details_selector_matches_pymdownx_details_markup(self):
        css = self._read("template/assets/css/main.css")
        self.assertIn("details {", css)
        self.assertNotIn("details.admonition", css)

    def test_tabbed_set_styled(self):
        css = self._read("template/assets/css/main.css")
        self.assertIn(".tabbed-set {", css)
        self.assertIn(".tabbed-labels {", css)

    def test_footnote_styled(self):
        css = self._read("template/assets/css/main.css")
        self.assertIn(".footnote {", css)
        self.assertIn(".footnote-ref {", css)

    def test_task_list_checkbox_styled(self):
        css = self._read("template/assets/css/main.css")
        self.assertIn(".task-list-item", css)

    def test_mark_and_kbd_styled(self):
        css = self._read("template/assets/css/main.css")
        self.assertIn("mark {", css)
        self.assertIn("kbd {", css)

    def test_twemoji_styled(self):
        css = self._read("template/assets/css/main.css")
        self.assertIn(".twemoji {", css)

    def test_shipped_minified_css_includes_admonition(self):
        css = self._read("mkdocs_simple_blog/assets/css/main.min.css")
        self.assertIn(".admonition{", css)
        self.assertNotIn("details.admonition", css)

    def test_markdown_extensions_configured(self):
        mkdocs_yml = self._read("mkdocs.yml")
        for extension in (
            "admonition",
            "footnotes",
            "attr_list",
            "def_list",
            "pymdownx.details",
            "pymdownx.tabbed",
            "pymdownx.tasklist",
            "pymdownx.emoji",
            "pymdownx.mark",
            "pymdownx.keys",
            "pymdownx.superfences",
        ):
            self.assertIn(extension, mkdocs_yml)
