blank_issues_enabled: false
contact_links:
  - name: 💬 General Question
    url: https://github.com/FernandoCelmer/mkdocs-simple-blog/discussions/categories/q-a
    about: Please ask and answer questions as a discussion thread