name: Conventional commit

on:
  pull_request:
    branches: ["main", "master"]

jobs:
  commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actionplatform/ci-github/conventional-commit@v1
